id = "void"
name = "Void"
description = "Void support."
version = "0.0.1"
schema_version = 1
authors = ["ge0mk"]
repository = "https://github.com/ge0mk/void"

[grammars.void]
repository = "https://github.com/ge0mk/tree-sitter-void"
commit = "82ba59e160925a646b9b3c5e3aad846124cd4d05"
