id = "void"
name = "Void"
description = "Void support."
version = "0.0.1"
schema_version = 1
authors = ["ge0mk"]
repository = "https://github.com/ge0mk/void"

[grammars.void]
repository = "https://github.com/ge0mk/tree-sitter-void"
commit = "197532c51e45945719d13f196021a9e8ab95376e"
